DTProj/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

base/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name="home"),
    path('register/', views.register, name="register"),
    path('bidding/<str:bidding_url>/', views.bidding, name="bidding"),
    path('agreement/<str:bidding_url>/', views.agreement, name="agreement"),
    path('auction/<str:bidding_url>/', views.auction, name="auction"),
    path('submit-form/', views.submit_form, name='submit_form'),
    # path('submit_bids/', views.submit_bids, name='submit_bids'),
    #path('validate_password/', views.validate_password, name='validate_password')


]

base/models.py
from django.db import models

# Create your models here.

class Participant(models.Model):
    IDParticipants = models.CharField(max_length=1000, default='none', unique=True)
    IDItems = models.CharField(max_length=1000, blank=True, null=True)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    
    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Item(models.Model):
    property_name = models.CharField(max_length=255)
    min_bid = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    Items_ID = models.CharField(max_length=1000, default='none')
    
    def __str__(self):
        return f"{self.property_name} --- {self.Items_ID}"

class Bidding (models.Model):
    IDParticipant = models.CharField(max_length=1000)
    total = models.FloatField()
    item1 = models.IntegerField(default = 0)
    item2 = models.IntegerField(default = 0)
    item3 = models.IntegerField(default = 0)
    item4 = models.IntegerField(default = 0)
    item5 = models.IntegerField(default = 0)
    item6 = models.IntegerField(default = 0)
    item7 = models.IntegerField(default = 0)
    item8 = models.IntegerField(default = 0)
    item9 = models.IntegerField(default = 0)
    item10 = models.IntegerField(default = 0)
    
    def __str__(self):
        return f"{self.IDParticipant}"

class Result(models.Model):
    fName = models.CharField(max_length=255)
    lName = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    IDparticipants = models.CharField(max_length=1000)
    item = models.CharField(max_length=1000)
    total_value = models.FloatField(default=0)
    fair_share = models.FloatField(default=0)
    pay = models.FloatField(default=0)
    get = models.FloatField(default=0)
    link = models.CharField(max_length=1000)

    def __str__(self):
        return f"{self.fName} {self.lName} --- {self.IDparticipants}"

base/forms.py
from django import forms
from .models import Participant, Item
from decimal import Decimal, InvalidOperation
from .utils import *

class ParticipantForm(forms.Form):
    participants = forms.JSONField()
    
    def save(self, items):
        participants_data = self.cleaned_data.get('participants', [])
        participants = []
        
        for participant_data in participants_data:
            participant = Participant(
                first_name=participant_data.get('firstName', ''),
                last_name=participant_data.get('lastName', ''),
                email=participant_data.get('email', ''),
                password=participant_data.get('password', ''),
                IDParticipants = generate_random_id(),
                IDItems = items
            )
            participants.append(participant)

        return participants


class PropertyForm(forms.Form):
    properties = forms.JSONField()

    def save(self, items, commit=True):
        properties_data = self.cleaned_data.get('properties', [])
        properties = []

        for property_data in properties_data:
            property_name = property_data.get('propertyName', '')
            min_bid = property_data.get('minBid', None)

            try:
                min_bid = Decimal(min_bid)
            except InvalidOperation:
                min_bid = None

            property_instance = Item(
                property_name=property_name,
                min_bid=min_bid,
                Items_ID = items
            )
            properties.append(property_instance)

        if commit:
            Item.objects.bulk_create(properties)

        return properties

base/views.py
from django.shortcuts import render, redirect, HttpResponse
from .forms import ParticipantForm, PropertyForm
from .models import Participant, Item, Bidding, Result
from .utils import *
from django.core.mail import send_mail, EmailMessage
from DTProj.settings import EMAIL_HOST_USER 
from django.urls import reverse
from django.http import HttpResponseForbidden
from django.contrib import messages
from decimal import Decimal
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from django.contrib.staticfiles import finders
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Table, TableStyle
from reportlab.lib import colors


def home(request):
    return render(request, 'main.html')

def register(request):
    return render (request, 'Register.html')

def submit_form(request):
    
    if request.method == 'POST':
        
        participant_form = ParticipantForm(request.POST)
        property_form = PropertyForm(request.POST)

        if participant_form.is_valid() and property_form.is_valid():
            
            items = generate_unique_id_item()
            
            participants = participant_form.save(items=items)
            for participant in participants:
                participant.save()
                
            properties = property_form.save(items=items)
            for property_instance in properties:
                property_instance.save()

            send_mail_to_participants(
                subject='Sealed Bid',
                sender='mainig87@gmail.com',
                item_id=items,
            )
            
            success = 'Registration has been successfully completed. Please check your email.'
            return render(request, 'successMsg.html', {'success_message': success})

def send_mail_to_participants(subject, sender, item_id, fail_silently=False):
    # Fetch the most recently registered participants with the same itemID from the database
    participants = Participant.objects.filter(IDItems=item_id)

    # Send email to recently registered participants
    for participant in participants:
        # Construct the personalized URL based on the participant's IDParticipants
        bidding_url = reverse('bidding', args=[participant.IDParticipants])

        # Create the email message
        email_message = f"Greetings {participant.first_name}!\n\n" \
                        f"Attached here is the link that you will be using for bidding:\n" \
                        f"http://127.0.0.1:8000{bidding_url}\n\n" \
                        f"Good luck and may you get what you desire!"

        # Send email to the participant
        send_mail(subject, email_message, sender, [participant.email], fail_silently=fail_silently)

def bidding(request, bidding_url):
    participant = Participant.objects.filter(IDParticipants=bidding_url).first()

    if participant:
        return render(request, 'JoinBidding.html', {'participant': participant})
    else:
        return HttpResponseForbidden("You are not authorized to access this page.")

def agreement(request, bidding_url):
    participant = Participant.objects.filter(IDParticipants=bidding_url).first()

    if not participant:
        return HttpResponseForbidden("You are not authorized to access this page.")

    if request.method == 'POST':
        entered_password = request.POST.get('password')
        participant_password = request.POST.get('participant_password')

        if entered_password == participant_password:
            return render(request, 'agtPage.html', {'participant': participant})
        
        else:
            messages.error(request, 'Incorrect password. Please try again.')
            return render(request, 'JoinBidding.html', {'participant': participant})
    
def auction(request, bidding_url):
    participants = Participant.objects.filter(IDParticipants=bidding_url).first()
    properties = Item.objects.filter(Items_ID=participants.IDItems)
    getItems = []

    if not participants:
        return HttpResponseForbidden("You are not authorized to access this page.")

    if request.method == 'POST':
        for property in properties:
            item_id = str(property.id)
            bid_amount_key = 'bid_amount_' + item_id
            bid_amount = request.POST.get(bid_amount_key)

            # Check if input bid is less than min bid amount
            if property.min_bid is not None and Decimal(bid_amount) < property.min_bid:
                messages.error(request, 'Bid is less than the minimum bid amount. Please try again.')
                return render(request, 'biddingPage.html', {'participant': participants, 'properties': properties, 'error_message': f'Bid must be equal to or greater than the minimum bid of ${property.min_bid} for {property.property_name}.'})

            getItems.append(bid_amount)

        # Dynamically calculate total and create Bidding instance
        total = sum(int(bid_amount) for bid_amount in getItems)
        bidding_data = {'IDParticipant': participants.IDParticipants, 'total': total}
        for i, bid_amount in enumerate(getItems, start=1):
            bidding_data[f'item{i}'] = int(bid_amount)

        CurrentAuction = Bidding(**bidding_data)
        CurrentAuction.save()

        participant = Participant.objects.get(IDParticipants=bidding_url)
        myItems = list(Item.objects.filter(Items_ID = participant.IDItems)) # Store the valued items in this list
        getParticipants = list(Participant.objects.filter(IDItems = participant.IDItems)) # To store the participants in the bid
        value_items =[] # Store all the items value of each participants 
        total_items = [] # Store the total value per participants which they declared for each item

        for get_participant in getParticipants:
            participant_check2 = Bidding.objects.filter(IDParticipant=get_participant.IDParticipants) #checking if the participant exist in the bid or not
            value_items1 =[] # 1d array that collect all the declared value per item
                
            #if exist then will now process the getting the information inputted
            if participant_check2.exists():
                currentParticipant = Bidding.objects.get(IDParticipant = get_participant.IDParticipants)             
                total_items.append(currentParticipant.total)
                if currentParticipant.item1 > 0:
                    value_items1.append(currentParticipant.item1)
                if currentParticipant.item2 > 0:
                    value_items1.append(currentParticipant.item2)
                if currentParticipant.item3 > 0:
                    value_items1.append(currentParticipant.item3)
                if currentParticipant.item4 > 0:
                    value_items1.append(currentParticipant.item4)
                if currentParticipant.item5 > 0:
                    value_items1.append(currentParticipant.item5)
                if currentParticipant.item6 > 0:
                    value_items1.append(currentParticipant.item6)
                if currentParticipant.item7 > 0:
                    value_items1.append(currentParticipant.item7)
                if currentParticipant.item8 > 0:
                    value_items1.append(currentParticipant.item8)
                if currentParticipant.item9 > 0:
                    value_items1.append(currentParticipant.item9)
                if currentParticipant.item10 > 0:
                    value_items1.append(currentParticipant.item10)
                value_items.append(value_items1) # an array that will store in an array
            else:
                success = 'You successfully placed  your bid. Please wait for the result in your email.'
                return render(request, 'successMsg.html', {'success_message': success})
                

        total_value = [] # total value awarded
        amount = [] # amount they get or pay
        fair_share =[] # fair share
        final_amount =[] # amount minus the surplus
        participant_wonId =[] # participant id
        participant_wonFirstName = [] # participant first name
        participant_wonLastName = [] # participant last name
        participant_wonEmail=[] # participant last name
        item_won=[] # what items they won
        participant_link = [] # link they will get when send
        pay = []
        get = []
        largest = []

        # loop for storing the information in an array from get_participants
        for getParticipant in getParticipants:
            participant_wonId.append(getParticipant.IDParticipants)
            participant_wonFirstName.append(getParticipant.first_name)
            participant_wonLastName.append(getParticipant.last_name)
            participant_wonEmail.append(getParticipant.email)
            participant_link.append(getParticipant.IDParticipants+getParticipant.IDItems)

        #loop for just getting the length of an array the values will change in the process   
        for x in range(len(getParticipants)):
            total_value.append(0)
            final_amount.append(0)
            amount.append(0)
            pay.append(0)
            get.append(0)
            item_won.append('')
            fairShare = total_items[x] / len(getParticipants)
            rounded = round(fairShare, 2)
            fair_share.append(rounded)
        
        count = 0
        while count < len(myItems):
            values = [sublist[count] for sublist in value_items]  # storing the subarray in a 2D array
            max_value = max(values)  # finding the highest value
            indices = [i for i, v in enumerate(values) if v == max_value]  # find indices with the highest value

            if len(indices) > 1:  # if there is a tiebreaker
                random_winner_index = random.choice(indices)
                myItemm = myItems[count]
                total_value[random_winner_index] += max_value

base/templates/JoinBidding.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Join Bidding</title>
    <link rel="stylesheet" href="{% static 'css/JoinBidding.css' %}">
    <link rel="stylesheet" media="screen" href="https://fontlibrary.org//face/heebo" type="text/css"/> 
    <script src="https://kit.fontawesome.com/b6ecc94894.js" crossorigin="anonymous"></script>
</head>
 
<body> 
    <section class="wave">   

        <div class="header"> 
            <img  class="logo" onclick="window.location.href='{% url 'home' %}'" src="{% static 'files/logo (4).png' %}" alt="logo">
            <p onclick="window.location.href='{% url 'home' %}'">Properties Settlement</p> 
        </div>

        <div id="preloader">
            <img src="{% static 'files/preloader.gif' %}" alt="Loading...">
        </div>

        <div class="content">

            <div class="joinContainer">
                <h1>Hello, {{ participant.first_name }}!</h1>
                <p>Welcome! You've been invited to Properties Settlement. Please input your unique password to begin your seamless property settlement.</p>

                <form id="passwordForm" method="post" action="{% url 'agreement'  bidding_url=participant.IDParticipants %}"> {% csrf_token %}
                    
                    <input type="hidden" name="participant_password" value="{{ participant.password }}">
                    <input type="hidden" name="participant" value="{{ participant.IDParticipants }}">

                    <div class="passDiv">
                        <input type="password" id="password" name="password" required>
                        <span>Password</span>
                        <div class="eye-icon" onclick="togglePassword()"><i class="fa-solid fa-eye" id="eye-icon"></i></div>
                    </div>

                    <div class="btn">
                        <a href="/"><button type="button" onclick="Cancel()">Cancel</button></a>
                        <button type="submit">Continue</button>
                    </div>
                    
                    <script>
                        {% if messages %}
                            var errorMessage = "{% for message in messages %}{{ message }}\n{% endfor %}";
                            alert(errorMessage);
                        {% endif %}
                    </script>

                </form>

            </div>
    
        </div>

        <span class="loader"><span class="loader-inner"></span></span>
    </section>
</body>
</html>
<script src="{% static 'js/JoinBidding.js' %}"></script>

base/templates/Register.html
<!DOCTYPE html> 
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bidding Registration</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/Register.css' %}">
    <link rel="stylesheet" media="screen" href="https://fontlibrary.org//face/heebo" type="text/css"/> 
    <script src="https://kit.fontawesome.com/b6ecc94894.js" crossorigin="anonymous"></script>

</head>
<body>
    <section class="wave">  
        <div class="header"> 
            <img  class="logo" onclick="window.location.href='{% url 'home' %}'" src="{% static 'files/logo (4).png' %}" alt="logo">
            <p onclick="window.location.href='{% url 'home' %}'">Properties Settlement</p> 
        </div>  

        <div class="content"> 
            <div id="preloader">
                <img src="{% static 'files/preloader.gif' %}" alt="Loading...">
            </div>
            <h1>Bidding Registration</h1>
            
            <form id="registrationForm" method="POST" action="{% url 'submit_form' %}"> {% csrf_token %}

                <div class="wrapper">
                    <div id="partCont" class="partCont">
                        <img src="{% static 'files/addPartiIcon.png' %}" alt="Participants Icon">
                        <label for="participantCount">Add Participants</label>
                        <p>Input the number of heiresses participating in the bidding. </p> 
                        <p class= 'minimum'>Mininum: 2 Participants</p>
                        <input type="number" id="participantCount" min="2" step="1" value= "3" onchange="validateParticipantCount()">
                    </div>
                    <div id="participantsContainer" class="participants-container"></div>
                    
                    <div class="propCont">
                        <img src="{% static 'files/addPropIcon.png' %}" alt="Properties Icon">
                        <label for="propertiesCount">Valued Properties</label>
                        <p>Input the quantity of valued properties eligible for bidding.</p>
                        <p class= 'minimum'>Mininum: 1 Property</p>
                        <input type="number" id="propertiesCount" min="1" max="10" step="1" value= "2" onchange="validatePropertyCount()">
                    </div>
                    <div id="propertiesContainer" class="properties-container"></div>
                </div>
                
                <!-- Added a hidden field to store JSON data -->
                <input type="hidden" name="participants" id="id_participants" />
                <input type="hidden" name="properties" id="id_properties" /> 

            </form>

        </div>  

        <button class="submitBtn" type="button" onclick="submitForm()">Submit</button>
        <button class= 'resetBtn' type="button" onclick="resetForm()">Reset</button> 

    </section>
    <script src="{% static 'js/Register.js' %}"></script> 
    
</body>
</html>

base/templates/agtPage.html
<!DOCTYPE html> 
{% load static %} 
<html> 
    <head>  
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">  
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <link rel="stylesheet" media="screen" href="https://fontlibrary.org//face/heebo" type="text/css"/>
        <title> Terms of Service Section In HTML and CSS </title> 
    </head>  

    <body>   

        <section class="wave1">  

        <div class="header"> 
            <img  class="logo2" onclick="window.location.href='{% url 'home' %}'" src="{% static 'files/logo (4).png' %}" alt="logo">
            <p onclick="window.location.href='{% url 'home' %}'">Properties Settlement</p> 
        </div> 
        
        <div id="preloader">
            <img src="{% static 'files/preloader.gif' %}" alt="Loading...">
        </div>

        <div class="wrapper flex_align_justify">
            <div class="Agreement">
                <div class="agr_item agr_head flex_align_justify">
                    <div class="logo1 flex_align_justify">
                        <img class="logo2" src="{% static 'files/logo (4).png' %}" alt="logo">
                    </div> 
                    
                    <div class="text1">
                        <h2>Agreement Terms and Condition</h2>
                        <p>Last updated on December 1 2023</p>
                    </div>
                </div> 
    
                <div class="agr_item agr_body">
                    <ol>
                        <li>
                            <h3>Terms of use</h3>
                            <p>By accessing Property's Settlement, you agree to follow our guidelines, ensuring a smooth inheritance settlement journey through our user-friendly online platform.</p>
                        </li>
                        <li>
                            <h3>Intellectual property rights</h3>
                            <p>All content and features on Property's Settlement are our intellectual property, and you are granted a limited license to use them; any unauthorized use is strictly prohibited.</p>
                        </li>
                        <li>
                            <h3>Prohibited activities</h3>
                            <p>Users are forbidden from engaging in activities such as unauthorized access, distribution of harmful code, privacy rights violation, impersonation, or any action compromising the platform's integrity.</p>
                        </li>
                        <li>
                            <h3>Termination clause</h3>
                            <p>Property's Settlement reserves the right to terminate or suspend user accounts at our discretion for reasons including guideline violations, suspicious activities, or non-compliance.</p>
                        </li>
                        <li>
                            <h3>Governing law</h3>
                            <p>These terms are governed by the laws of the Republic of the Philippines, specifically the Civil Code of the Philippines (Republic Act No. 386), and any disputes will be subject to the exclusive jurisdiction of the courts in the Philippines.</p>
                        </li>
                    </ol>
                </div>
                <div class="agr_item agr_foot flex_align">
                    <a href="/"><button class="decline_btn">Decline</button></a>
                    <a href="{% url 'auction' bidding_url=participant.IDParticipants %}"><button class="accept_btn">Accept</button></a>
                </div>
            </div>
        </div>
        </section>
    </body>
    </html>
    
    <script src="{% static 'js/main.js' %}"></script>

base/templates/biddingPage.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bidding Room</title>
    <link rel="stylesheet" href="{% static 'css/biddingPage.css' %}">  
    <script src="https://kit.fontawesome.com/b6ecc94894.js" crossorigin="anonymous"></script> 
    <script src="{% static 'js/Register.js' %}"></script>  
    <script src="{% static 'js/biddingPage.js' %}"></script>  
    <link rel="stylesheet" media="screen" href="https://fontlibrary.org//face/heebo" type="text/css"/> 
</head> 

<body>
    <section class="wave">  
    <div class="header"> 
        <img  class="logo" onclick="window.location.href='{% url 'home' %}'" src="{% static 'files/logo (4).png' %}" alt="logo">
        <p onclick="window.location.href='{% url 'home' %}'">Properties Settlement</p> 
    </div>

    <div id="preloader">
        <img src="{% static 'files/preloader.gif' %}" alt="Loading...">
    </div>

    {% comment %} <section method="post" action="{% url 'submit_bids' %}"> {% csrf_token %} {% endcomment %}
    <form method="post" action="{% url 'auction' bidding_url=participant.IDParticipants %}"> {% csrf_token %}

        <div class="content">
            <h2>Place your Bid</h2>  

            <div id="propertyNames">

                {% for property in properties %}
                    <div class="property-container">
                        <div class="property-box"> 

                            <span class="count">{{ forloop.counter }}</span>
                            <h3 class="propHead">{{ property.property_name }}</h3>
                            <p>Minimum Bid: {% if property.min_bid %}${{ property.min_bid }}{% else %}No minimum{% endif %}</p>                            
                            <input type="hidden" name="item_id" value="{{ item.id }}">
                            <input type="number" class="bid-input"step="0.01" name="bid_amount_{{ property.id }}" placeholder="Enter Your Bid" required>

                        </div>
                    </div>
                {% endfor %}

            </div>

        </div>

        <script>
            {% if messages %}
                var errorMessage = "{% for message in messages %}{{ message }}\n{% endfor %}";
                alert(errorMessage);
            {% endif %}
        </script>

        <button class= 'submitBtn' type="submit">Submit</button> 
    </section>
    </form> 


</body>

</html>

base/templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>  
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Properties Settlement</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}"> 
    <link rel="stylesheet" media="screen" href="https://fontlibrary.org//face/heebo" type="text/css"/> 

</head>
<body>  
    <div id="preloader">
        <img src="{% static 'files/preloader.gif' %}" alt="Loading...">
    </div>   

    <div class="content">  

        <div class="sitename"> 
            <p>Properties Settlement</p> 
        </div>   

        <div class="description">
            <p>Embark on a seamless inheritance settlement journey with Property's Settlement.  
                Our online platform employs the Sealed Bid method, guaranteeing a fair and transparent distribution process.  
                Experience efficiency, clarity, and stress-free property settlements like never before.</p>
        </div>

        <!-- CONTENT GOES HERE -->   
        <div class="logo">
            <img onclick="window.location.href='{% url 'home' %}'" src="{% static 'files/logo (4).png' %}" alt="logo">
        </div>  
        <a class="register" href="register/"><button>  Register</button></a>
        </div> 

         <section class="wave"></section> 
         <div class="container">  
            <p>Developers</p>
            
            <div class="devimgs devimgs1">
                <a href="https://www.facebook.com/canlas.yul">
                    <h5>Yul</h5>
                    <img src="{% static 'files/yul.jpg' %}" alt="Yul">
                </a>
            </div>
    
            <div class="devimgs devimgs2">
                <a href="https://www.facebook.com/EriiSsi">
                    <h5>Ericka</h5>
                    <img src="{% static 'files/ericka.jpg' %}" alt="Ericka">
                </a>
            </div>
            
            <div class="devimgs devimgs3">
                <a href="https://www.facebook.com/graceanne.garchitorena/">
                    <h5>Grace</h5>
                    <img src="{% static 'files/grace.jpg' %}" alt="Grace">
                </a>
            </div>
            
            <div class="devimgs devimgs4">
                <a href="https://www.facebook.com/debidabadu">
                    <h5>David</h5>
                    <img src="{% static 'files/david.jpg' %}" alt="David">
                </a>
            </div>
            
            <div class="devimgs devimgs5">
                <a href="https://www.facebook.com/EnzoPogi.09">
                    <h5>Lorenzo</h5>
                    <img src="{% static 'files/enzo.png' %}" alt="Lorenzo">
                </a>
            </div> 
        </div>  
            
            <img src="{% static 'files/logo (3).png' %}" class="logo3">
        
        <div class="bottompage">   
           <p>Find us on:</p> 
            <a href="https://www.facebook.com/debidabadu"><img src="{% static 'files/fb.png' %}"></a>
            <img src="{% static 'files/gmail.png' %}">    
            <img src="{% static 'files/x.png' %}">  
        </div>  

</body>
</html>

<script src="{% static 'js/main.js' %}"></script>

base/templates/successMsg.html
<!DOCTYPE html> 
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
    <link rel="stylesheet" media="screen" href="https://fontlibrary.org//face/heebo" type="text/css"/>  
    <link rel="icon" type="image/png" href="{% static 'files/logo (3).png' %}"/>
    <title>Success Message</title>
    
    <link rel="stylesheet" href="{% static 'css/successMsg.css' %}">
</head>
<body>
    <div class="success-message-container"> 
        <img class="check" src="{% static 'files/check.gif' %}"> 
        <h1>All Done!</h1> 
        <p>{{ success_message }}</p> 
        <button class="okay-button" onclick="window.location.href='{% url 'home' %}'">Ok</button>
    </div> 

    <script>
        function closePage() {
            window.close();
        }
    </script>
</body>
</html>